// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBI4AQxgkN4zG2_v660y4bFKYfSGnqbxQ4',
    appId: '1:294710809838:web:your-web-app-id',
    messagingSenderId: '294710809838',
    projectId: 'social-link-downloader',
    authDomain: 'social-link-downloader.firebaseapp.com',
    storageBucket: 'social-link-downloader.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBI4AQxgkN4zG2_v660y4bFKYfSGnqbxQ4',
    appId: '1:294710809838:android:e0b24ed1037ad1a26acfff',
    messagingSenderId: '294710809838',
    projectId: 'social-link-downloader',
    storageBucket: 'social-link-downloader.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBI4AQxgkN4zG2_v660y4bFKYfSGnqbxQ4',
    appId: '1:294710809838:ios:your-ios-app-id',
    messagingSenderId: '294710809838',
    projectId: 'social-link-downloader',
    storageBucket: 'social-link-downloader.firebasestorage.app',
    iosBundleId: 'com.example.socialMediaDownloder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBI4AQxgkN4zG2_v660y4bFKYfSGnqbxQ4',
    appId: '1:294710809838:ios:your-macos-app-id',
    messagingSenderId: '294710809838',
    projectId: 'social-link-downloader',
    storageBucket: 'social-link-downloader.firebasestorage.app',
    iosBundleId: 'com.example.socialMediaDownloder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBI4AQxgkN4zG2_v660y4bFKYfSGnqbxQ4',
    appId: '1:294710809838:web:your-windows-app-id',
    messagingSenderId: '294710809838',
    projectId: 'social-link-downloader',
    authDomain: 'social-link-downloader.firebaseapp.com',
    storageBucket: 'social-link-downloader.firebasestorage.app',
  );
}